GET http://localhost:5000/users
###
POST http://localhost:5000/users
Content-Type: application/json

{
  "firstname": "Mounir",
  "lastname": "Mekoui",
  "email": "mounir.mekoui@gmail.com",
  "password": "password123"
}

###
GET http://localhost:5000/vehicles